#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogAndCatAPI.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DogAndCatDBQA")]
	public partial class DogAndCatDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DogAndCatDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DogAndCatDBQAConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DogAndCatDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DogAndCatDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DogAndCatDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DogAndCatDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_Check_Captcha_AndUser")]
		public ISingleResult<API_Check_Captcha_AndUserResult> API_Check_Captcha_AndUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APITransaction", DbType="UniqueIdentifier")] System.Nullable<System.Guid> pRM_APITransaction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_UserGuid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> pRM_UserGuid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_UserUniqueIdentity", DbType="NVarChar(250)")] string pRM_UserUniqueIdentity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_CreateDate", DbType="DateTime")] System.Nullable<System.DateTime> pRM_CreateDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_CreateDateISR", DbType="DateTime")] System.Nullable<System.DateTime> pRM_CreateDateISR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_MaxAllowed", DbType="Int")] System.Nullable<int> pRM_MaxAllowed, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_MinutesToExpired", DbType="Int")] System.Nullable<int> pRM_MinutesToExpired, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_IP", DbType="VarChar(50)")] string pRM_IP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ProjectID", DbType="Int")] System.Nullable<int> pRM_ProjectID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_APITransaction, pRM_UserGuid, pRM_UserUniqueIdentity, pRM_CreateDate, pRM_CreateDateISR, pRM_MaxAllowed, pRM_MinutesToExpired, pRM_IP, pRM_ProjectID);
			return ((ISingleResult<API_Check_Captcha_AndUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_Internal_Unique_Identity_AddUpdate")]
		public int API_Internal_Unique_Identity_AddUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APITransaction", DbType="UniqueIdentifier")] System.Nullable<System.Guid> pRM_APITransaction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_UserUniqueIdentity", DbType="NVarChar(250)")] string pRM_UserUniqueIdentity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_CreateDate", DbType="DateTime")] System.Nullable<System.DateTime> pRM_CreateDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_CreateDateISR", DbType="DateTime")] System.Nullable<System.DateTime> pRM_CreateDateISR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_MaxAllowed", DbType="Int")] System.Nullable<int> pRM_Unique_MaxAllowed, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_MinutesToExpired", DbType="Int")] System.Nullable<int> pRM_Unique_MinutesToExpired)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_APITransaction, pRM_UserUniqueIdentity, pRM_CreateDate, pRM_CreateDateISR, pRM_Unique_MaxAllowed, pRM_Unique_MinutesToExpired);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_IsAlive_UniqueUser")]
		public ISingleResult<API_IsAlive_UniqueUserResult> API_IsAlive_UniqueUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APITransaction", DbType="UniqueIdentifier")] System.Nullable<System.Guid> pRM_APITransaction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_UserUniqueIdentity", DbType="NVarChar(250)")] string pRM_UserUniqueIdentity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_IP", DbType="VarChar(50)")] string pRM_IP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_UA", DbType="NVarChar(2000)")] string pRM_UA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_PlatformID", DbType="Int")] System.Nullable<int> pRM_PlatformID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_CreateDate", DbType="DateTime")] System.Nullable<System.DateTime> pRM_CreateDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_CreateDateISR", DbType="DateTime")] System.Nullable<System.DateTime> pRM_CreateDateISR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_IP_MaxAllowed", DbType="Int")] System.Nullable<int> pRM_IP_MaxAllowed, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_IP_MinutesToExpired", DbType="Int")] System.Nullable<int> pRM_IP_MinutesToExpired, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_AddToIPIdentity", DbType="Int")] System.Nullable<int> pRM_AddToIPIdentity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_MaxAllowed", DbType="Int")] System.Nullable<int> pRM_Unique_MaxAllowed, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_MinutesToExpired", DbType="Int")] System.Nullable<int> pRM_Unique_MinutesToExpired, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ProjectID", DbType="Int")] System.Nullable<int> pRM_ProjectID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_APITransaction, pRM_UserUniqueIdentity, pRM_IP, pRM_UA, pRM_PlatformID, pRM_CreateDate, pRM_CreateDateISR, pRM_IP_MaxAllowed, pRM_IP_MinutesToExpired, pRM_AddToIPIdentity, pRM_Unique_MaxAllowed, pRM_Unique_MinutesToExpired, pRM_ProjectID);
			return ((ISingleResult<API_IsAlive_UniqueUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_Log_Insert")]
		public int API_Log_Insert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ActionType", DbType="Int")] System.Nullable<int> pRM_ActionType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_LogType", DbType="Int")] System.Nullable<int> pRM_LogType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_InnerLogType", DbType="Int")] System.Nullable<int> pRM_InnerLogType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_MSG", DbType="NVarChar(MAX)")] string pRM_MSG, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_MSG2", DbType="NVarChar(MAX)")] string pRM_MSG2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Error", DbType="NVarChar(MAX)")] string pRM_Error, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Critical", DbType="Bit")] System.Nullable<bool> pRM_Critical, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Refferer", DbType="NVarChar(1000)")] string pRM_Refferer, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_IP", DbType="VarChar(50)")] string pRM_IP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_UA", DbType="NVarChar(4000)")] string pRM_UA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APICreateDate", DbType="DateTime")] System.Nullable<System.DateTime> pRM_APICreateDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APICreateDate_ISR", DbType="DateTime")] System.Nullable<System.DateTime> pRM_APICreateDate_ISR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APITransaction", DbType="UniqueIdentifier")] System.Nullable<System.Guid> pRM_APITransaction, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Instance", DbType="VarChar(100)")] string pRM_Instance, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Identifier", DbType="VarChar(100)")] string pRM_Identifier, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ProjectID", DbType="Int")] System.Nullable<int> pRM_ProjectID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_ActionType, pRM_LogType, pRM_InnerLogType, pRM_MSG, pRM_MSG2, pRM_Error, pRM_Critical, pRM_Refferer, pRM_IP, pRM_UA, pRM_APICreateDate, pRM_APICreateDate_ISR, pRM_APITransaction, pRM_Instance, pRM_Identifier, pRM_ProjectID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_Unique_Identity_AddUpdate")]
		public ISingleResult<API_Unique_Identity_AddUpdateResult> API_Unique_Identity_AddUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APITransaction", DbType="UniqueIdentifier")] System.Nullable<System.Guid> pRM_APITransaction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_UserUniqueIdentity", DbType="NVarChar(250)")] string pRM_UserUniqueIdentity, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_CreateDate", DbType="DateTime")] System.Nullable<System.DateTime> pRM_CreateDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_CreateDateISR", DbType="DateTime")] System.Nullable<System.DateTime> pRM_CreateDateISR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_MaxAllowed", DbType="Int")] System.Nullable<int> pRM_Unique_MaxAllowed, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_MinutesToExpired", DbType="Int")] System.Nullable<int> pRM_Unique_MinutesToExpired, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ProjectID", DbType="Int")] System.Nullable<int> pRM_ProjectID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_APITransaction, pRM_UserUniqueIdentity, pRM_CreateDate, pRM_CreateDateISR, pRM_Unique_MaxAllowed, pRM_Unique_MinutesToExpired, pRM_ProjectID);
			return ((ISingleResult<API_Unique_Identity_AddUpdateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_UI_UserResponse_Get")]
		public ISingleResult<API_UI_UserResponse_GetResult> API_UI_UserResponse_Get()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<API_UI_UserResponse_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_Lead_Update_CouponMSG")]
		public ISingleResult<API_Lead_Update_CouponMSGResult> API_Lead_Update_CouponMSG([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ID", DbType="BigInt")] System.Nullable<long> pRM_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ResponseMSG", DbType="NVarChar(4000)")] string pRM_ResponseMSG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_SuccessCoupon", DbType="Bit")] System.Nullable<bool> pRM_SuccessCoupon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_ID, pRM_ResponseMSG, pRM_SuccessCoupon);
			return ((ISingleResult<API_Lead_Update_CouponMSGResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_Validate_Registered_User")]
		public ISingleResult<API_Validate_Registered_UserResult> API_Validate_Registered_User([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ProjectID", DbType="Int")] System.Nullable<int> pRM_ProjectID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Email", DbType="NVarChar(100)")] string pRM_Email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_ProjectID, pRM_Email);
			return ((ISingleResult<API_Validate_Registered_UserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_Project_Get")]
		public ISingleResult<API_Project_GetResult> API_Project_Get([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_RenewTokens", DbType="Bit")] System.Nullable<bool> pRM_RenewTokens)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_RenewTokens);
			return ((ISingleResult<API_Project_GetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.API_Lead_Insert")]
		public ISingleResult<API_Lead_InsertResult> API_Lead_Insert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APITransaction", DbType="UniqueIdentifier")] System.Nullable<System.Guid> pRM_APITransaction, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_User_Identity", DbType="NVarChar(250)")] string pRM_Unique_User_Identity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_PlatformID", DbType="Int")] System.Nullable<int> pRM_PlatformID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_IP", DbType="NVarChar(50)")] string pRM_IP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_UA", DbType="NVarChar(MAX)")] string pRM_UA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APICreateDate", DbType="DateTime")] System.Nullable<System.DateTime> pRM_APICreateDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_APICreateDateISR", DbType="DateTime")] System.Nullable<System.DateTime> pRM_APICreateDateISR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_MaxRejectCountToLock", DbType="Int")] System.Nullable<int> pRM_MaxRejectCountToLock, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Captcha", DbType="NVarChar(1000)")] string pRM_Captcha, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_MaxAllowed", DbType="Int")] System.Nullable<int> pRM_Unique_MaxAllowed, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Unique_MinutesToExpired", DbType="Int")] System.Nullable<int> pRM_Unique_MinutesToExpired, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_ProjectID", DbType="Int")] System.Nullable<int> pRM_ProjectID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_FName", DbType="NVarChar(100)")] string pRM_FName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_LName", DbType="NVarChar(100)")] string pRM_LName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Email", DbType="NVarChar(100)")] string pRM_Email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Phone", DbType="NVarChar(100)")] string pRM_Phone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_City", DbType="NVarChar(100)")] string pRM_City, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Street", DbType="NVarChar(100)")] string pRM_Street, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Number", DbType="NVarChar(100)")] string pRM_Number, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_FlatNumber", DbType="NVarChar(100)")] string pRM_FlatNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_POBox", DbType="NVarChar(100)")] string pRM_POBox, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_Regulation", DbType="Bit")] System.Nullable<bool> pRM_Regulation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_AcceptContent", DbType="Bit")] System.Nullable<bool> pRM_AcceptContent, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_PetType", DbType="Int")] System.Nullable<int> pRM_PetType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_PetBDate", DbType="DateTime")] System.Nullable<System.DateTime> pRM_PetBDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_IP_MaxAllowed", DbType="Int")] System.Nullable<int> pRM_IP_MaxAllowed, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_IP_MinutesToExpired", DbType="Int")] System.Nullable<int> pRM_IP_MinutesToExpired, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRM_AddToIPIdentity", DbType="Int")] System.Nullable<int> pRM_AddToIPIdentity)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRM_APITransaction, pRM_Unique_User_Identity, pRM_PlatformID, pRM_IP, pRM_UA, pRM_APICreateDate, pRM_APICreateDateISR, pRM_MaxRejectCountToLock, pRM_Captcha, pRM_Unique_MaxAllowed, pRM_Unique_MinutesToExpired, pRM_ProjectID, pRM_FName, pRM_LName, pRM_Email, pRM_Phone, pRM_City, pRM_Street, pRM_Number, pRM_FlatNumber, pRM_POBox, pRM_Regulation, pRM_AcceptContent, pRM_PetType, pRM_PetBDate, pRM_IP_MaxAllowed, pRM_IP_MinutesToExpired, pRM_AddToIPIdentity);
			return ((ISingleResult<API_Lead_InsertResult>)(result.ReturnValue));
		}
	}
	
	public partial class API_Check_Captcha_AndUserResult
	{
		
		private System.Nullable<bool> _NeedCaptcha;
		
		private System.Nullable<int> _MaxAllowed;
		
		private System.Nullable<int> _IPCount;
		
		private System.Nullable<System.DateTime> _ExpiredDate;
		
		private System.Nullable<long> _UserUniqueID;
		
		private System.Nullable<int> _UserUniqueRejctCount;
		
		private System.Nullable<System.DateTime> _UserUniqueRejctUntil;
		
		public API_Check_Captcha_AndUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedCaptcha", DbType="Bit")]
		public System.Nullable<bool> NeedCaptcha
		{
			get
			{
				return this._NeedCaptcha;
			}
			set
			{
				if ((this._NeedCaptcha != value))
				{
					this._NeedCaptcha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAllowed", DbType="Int")]
		public System.Nullable<int> MaxAllowed
		{
			get
			{
				return this._MaxAllowed;
			}
			set
			{
				if ((this._MaxAllowed != value))
				{
					this._MaxAllowed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPCount", DbType="Int")]
		public System.Nullable<int> IPCount
		{
			get
			{
				return this._IPCount;
			}
			set
			{
				if ((this._IPCount != value))
				{
					this._IPCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiredDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiredDate
		{
			get
			{
				return this._ExpiredDate;
			}
			set
			{
				if ((this._ExpiredDate != value))
				{
					this._ExpiredDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUniqueID", DbType="BigInt")]
		public System.Nullable<long> UserUniqueID
		{
			get
			{
				return this._UserUniqueID;
			}
			set
			{
				if ((this._UserUniqueID != value))
				{
					this._UserUniqueID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUniqueRejctCount", DbType="Int")]
		public System.Nullable<int> UserUniqueRejctCount
		{
			get
			{
				return this._UserUniqueRejctCount;
			}
			set
			{
				if ((this._UserUniqueRejctCount != value))
				{
					this._UserUniqueRejctCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserUniqueRejctUntil", DbType="DateTime")]
		public System.Nullable<System.DateTime> UserUniqueRejctUntil
		{
			get
			{
				return this._UserUniqueRejctUntil;
			}
			set
			{
				if ((this._UserUniqueRejctUntil != value))
				{
					this._UserUniqueRejctUntil = value;
				}
			}
		}
	}
	
	public partial class API_IsAlive_UniqueUserResult
	{
		
		private System.Nullable<bool> _NeedCaptcha_DUE_IP;
		
		private System.Nullable<int> _MaxAllowed_IP;
		
		private System.Nullable<int> _Count_IP;
		
		private System.Nullable<System.DateTime> _ExpiredDate_IP;
		
		private System.Nullable<System.Guid> _NewUserGuid;
		
		private System.Nullable<System.Guid> _UserToken;
		
		private System.Nullable<System.Guid> _StaticToken;
		
		private System.Nullable<int> _Count_MACUnique;
		
		private System.Nullable<int> _MaxAllowed_MACUnique;
		
		private System.Nullable<System.DateTime> _ExpiredDate_MACUnique;
		
		private System.Nullable<bool> _Unique_Reject;
		
		public API_IsAlive_UniqueUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedCaptcha_DUE_IP", DbType="Bit")]
		public System.Nullable<bool> NeedCaptcha_DUE_IP
		{
			get
			{
				return this._NeedCaptcha_DUE_IP;
			}
			set
			{
				if ((this._NeedCaptcha_DUE_IP != value))
				{
					this._NeedCaptcha_DUE_IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAllowed_IP", DbType="Int")]
		public System.Nullable<int> MaxAllowed_IP
		{
			get
			{
				return this._MaxAllowed_IP;
			}
			set
			{
				if ((this._MaxAllowed_IP != value))
				{
					this._MaxAllowed_IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count_IP", DbType="Int")]
		public System.Nullable<int> Count_IP
		{
			get
			{
				return this._Count_IP;
			}
			set
			{
				if ((this._Count_IP != value))
				{
					this._Count_IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiredDate_IP", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiredDate_IP
		{
			get
			{
				return this._ExpiredDate_IP;
			}
			set
			{
				if ((this._ExpiredDate_IP != value))
				{
					this._ExpiredDate_IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewUserGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NewUserGuid
		{
			get
			{
				return this._NewUserGuid;
			}
			set
			{
				if ((this._NewUserGuid != value))
				{
					this._NewUserGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserToken", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserToken
		{
			get
			{
				return this._UserToken;
			}
			set
			{
				if ((this._UserToken != value))
				{
					this._UserToken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaticToken", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StaticToken
		{
			get
			{
				return this._StaticToken;
			}
			set
			{
				if ((this._StaticToken != value))
				{
					this._StaticToken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count_MACUnique", DbType="Int")]
		public System.Nullable<int> Count_MACUnique
		{
			get
			{
				return this._Count_MACUnique;
			}
			set
			{
				if ((this._Count_MACUnique != value))
				{
					this._Count_MACUnique = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAllowed_MACUnique", DbType="Int")]
		public System.Nullable<int> MaxAllowed_MACUnique
		{
			get
			{
				return this._MaxAllowed_MACUnique;
			}
			set
			{
				if ((this._MaxAllowed_MACUnique != value))
				{
					this._MaxAllowed_MACUnique = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiredDate_MACUnique", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiredDate_MACUnique
		{
			get
			{
				return this._ExpiredDate_MACUnique;
			}
			set
			{
				if ((this._ExpiredDate_MACUnique != value))
				{
					this._ExpiredDate_MACUnique = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unique_Reject", DbType="Bit")]
		public System.Nullable<bool> Unique_Reject
		{
			get
			{
				return this._Unique_Reject;
			}
			set
			{
				if ((this._Unique_Reject != value))
				{
					this._Unique_Reject = value;
				}
			}
		}
	}
	
	public partial class API_Unique_Identity_AddUpdateResult
	{
		
		private System.Nullable<int> _TotalNow;
		
		private System.Nullable<System.DateTime> _ExpiredDate;
		
		private System.Nullable<int> _MaxAllowed;
		
		public API_Unique_Identity_AddUpdateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalNow", DbType="Int")]
		public System.Nullable<int> TotalNow
		{
			get
			{
				return this._TotalNow;
			}
			set
			{
				if ((this._TotalNow != value))
				{
					this._TotalNow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiredDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiredDate
		{
			get
			{
				return this._ExpiredDate;
			}
			set
			{
				if ((this._ExpiredDate != value))
				{
					this._ExpiredDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAllowed", DbType="Int")]
		public System.Nullable<int> MaxAllowed
		{
			get
			{
				return this._MaxAllowed;
			}
			set
			{
				if ((this._MaxAllowed != value))
				{
					this._MaxAllowed = value;
				}
			}
		}
	}
	
	public partial class API_UI_UserResponse_GetResult
	{
		
		private int _ID;
		
		private string _Text;
		
		private int _ProjectID;
		
		public API_UI_UserResponse_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectID", DbType="Int NOT NULL")]
		public int ProjectID
		{
			get
			{
				return this._ProjectID;
			}
			set
			{
				if ((this._ProjectID != value))
				{
					this._ProjectID = value;
				}
			}
		}
	}
	
	public partial class API_Lead_Update_CouponMSGResult
	{
		
		private System.Nullable<int> _DBResult;
		
		public API_Lead_Update_CouponMSGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBResult", DbType="Int")]
		public System.Nullable<int> DBResult
		{
			get
			{
				return this._DBResult;
			}
			set
			{
				if ((this._DBResult != value))
				{
					this._DBResult = value;
				}
			}
		}
	}
	
	public partial class API_Validate_Registered_UserResult
	{
		
		private long _ID;
		
		private System.DateTime _InsertDate;
		
		private System.DateTime _InsertDateISR;
		
		private System.DateTime _LastVisitTime;
		
		private System.DateTime _LastVisitTimeISR;
		
		private string _Unique_User_Identity;
		
		private string _IP;
		
		private string _UA;
		
		private int _PlatformID;
		
		private int _Visit_Count;
		
		private int _RejectedCount;
		
		private System.Nullable<System.DateTime> _RejectedUntilDate;
		
		private int _ProjectID;
		
		private System.Nullable<bool> _PreRegister;
		
		public API_Validate_Registered_UserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDate", DbType="DateTime NOT NULL")]
		public System.DateTime InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this._InsertDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDateISR", DbType="DateTime NOT NULL")]
		public System.DateTime InsertDateISR
		{
			get
			{
				return this._InsertDateISR;
			}
			set
			{
				if ((this._InsertDateISR != value))
				{
					this._InsertDateISR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitTime", DbType="DateTime NOT NULL")]
		public System.DateTime LastVisitTime
		{
			get
			{
				return this._LastVisitTime;
			}
			set
			{
				if ((this._LastVisitTime != value))
				{
					this._LastVisitTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitTimeISR", DbType="DateTime NOT NULL")]
		public System.DateTime LastVisitTimeISR
		{
			get
			{
				return this._LastVisitTimeISR;
			}
			set
			{
				if ((this._LastVisitTimeISR != value))
				{
					this._LastVisitTimeISR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unique_User_Identity", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Unique_User_Identity
		{
			get
			{
				return this._Unique_User_Identity;
			}
			set
			{
				if ((this._Unique_User_Identity != value))
				{
					this._Unique_User_Identity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this._IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UA", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string UA
		{
			get
			{
				return this._UA;
			}
			set
			{
				if ((this._UA != value))
				{
					this._UA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlatformID", DbType="Int NOT NULL")]
		public int PlatformID
		{
			get
			{
				return this._PlatformID;
			}
			set
			{
				if ((this._PlatformID != value))
				{
					this._PlatformID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Count", DbType="Int NOT NULL")]
		public int Visit_Count
		{
			get
			{
				return this._Visit_Count;
			}
			set
			{
				if ((this._Visit_Count != value))
				{
					this._Visit_Count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectedCount", DbType="Int NOT NULL")]
		public int RejectedCount
		{
			get
			{
				return this._RejectedCount;
			}
			set
			{
				if ((this._RejectedCount != value))
				{
					this._RejectedCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectedUntilDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RejectedUntilDate
		{
			get
			{
				return this._RejectedUntilDate;
			}
			set
			{
				if ((this._RejectedUntilDate != value))
				{
					this._RejectedUntilDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectID", DbType="Int NOT NULL")]
		public int ProjectID
		{
			get
			{
				return this._ProjectID;
			}
			set
			{
				if ((this._ProjectID != value))
				{
					this._ProjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreRegister", DbType="Bit")]
		public System.Nullable<bool> PreRegister
		{
			get
			{
				return this._PreRegister;
			}
			set
			{
				if ((this._PreRegister != value))
				{
					this._PreRegister = value;
				}
			}
		}
	}
	
	public partial class API_Project_GetResult
	{
		
		private int _ID;
		
		private string _Text;
		
		private System.Guid _Token;
		
		private System.Guid _OldToken;
		
		private System.DateTime _UpdateDate;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndIncludeDate;
		
		private string _ServerMSG;
		
		private bool _Enabled;
		
		private System.Nullable<int> _Coupon_SiteID;
		
		private System.Nullable<int> _Coupon_GroupID;
		
		private string _Coupon_APIPassword;
		
		private string _Coupon_EmailID;
		
		private string _SenderEmailAddress;
		
		private string _MessageContent;
		
		private string _MessageSubject;
		
		private string _MessageInnerName;
		
		public API_Project_GetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Token
		{
			get
			{
				return this._Token;
			}
			set
			{
				if ((this._Token != value))
				{
					this._Token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldToken", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OldToken
		{
			get
			{
				return this._OldToken;
			}
			set
			{
				if ((this._OldToken != value))
				{
					this._OldToken = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndIncludeDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndIncludeDate
		{
			get
			{
				return this._EndIncludeDate;
			}
			set
			{
				if ((this._EndIncludeDate != value))
				{
					this._EndIncludeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerMSG", DbType="NVarChar(200)")]
		public string ServerMSG
		{
			get
			{
				return this._ServerMSG;
			}
			set
			{
				if ((this._ServerMSG != value))
				{
					this._ServerMSG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enabled", DbType="Bit NOT NULL")]
		public bool Enabled
		{
			get
			{
				return this._Enabled;
			}
			set
			{
				if ((this._Enabled != value))
				{
					this._Enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_SiteID", DbType="Int")]
		public System.Nullable<int> Coupon_SiteID
		{
			get
			{
				return this._Coupon_SiteID;
			}
			set
			{
				if ((this._Coupon_SiteID != value))
				{
					this._Coupon_SiteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_GroupID", DbType="Int")]
		public System.Nullable<int> Coupon_GroupID
		{
			get
			{
				return this._Coupon_GroupID;
			}
			set
			{
				if ((this._Coupon_GroupID != value))
				{
					this._Coupon_GroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_APIPassword", DbType="NVarChar(20)")]
		public string Coupon_APIPassword
		{
			get
			{
				return this._Coupon_APIPassword;
			}
			set
			{
				if ((this._Coupon_APIPassword != value))
				{
					this._Coupon_APIPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupon_EmailID", DbType="NVarChar(20)")]
		public string Coupon_EmailID
		{
			get
			{
				return this._Coupon_EmailID;
			}
			set
			{
				if ((this._Coupon_EmailID != value))
				{
					this._Coupon_EmailID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderEmailAddress", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SenderEmailAddress
		{
			get
			{
				return this._SenderEmailAddress;
			}
			set
			{
				if ((this._SenderEmailAddress != value))
				{
					this._SenderEmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageContent", DbType="NVarChar(4000)")]
		public string MessageContent
		{
			get
			{
				return this._MessageContent;
			}
			set
			{
				if ((this._MessageContent != value))
				{
					this._MessageContent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageSubject", DbType="NVarChar(200)")]
		public string MessageSubject
		{
			get
			{
				return this._MessageSubject;
			}
			set
			{
				if ((this._MessageSubject != value))
				{
					this._MessageSubject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageInnerName", DbType="NVarChar(100)")]
		public string MessageInnerName
		{
			get
			{
				return this._MessageInnerName;
			}
			set
			{
				if ((this._MessageInnerName != value))
				{
					this._MessageInnerName = value;
				}
			}
		}
	}
	
	public partial class API_Lead_InsertResult
	{
		
		private System.Nullable<int> _DBResult;
		
		private System.Nullable<long> _UniqueUserID;
		
		private System.Nullable<long> _LeadID;
		
		private System.Nullable<bool> _NewUser;
		
		private System.Nullable<bool> _NeedCaptcha_DUE_IP;
		
		private System.Nullable<int> _MaxAllowed_IP;
		
		private System.Nullable<int> _Count_IP;
		
		private System.Nullable<System.DateTime> _ExpiredIPAt;
		
		public API_Lead_InsertResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DBResult", DbType="Int")]
		public System.Nullable<int> DBResult
		{
			get
			{
				return this._DBResult;
			}
			set
			{
				if ((this._DBResult != value))
				{
					this._DBResult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueUserID", DbType="BigInt")]
		public System.Nullable<long> UniqueUserID
		{
			get
			{
				return this._UniqueUserID;
			}
			set
			{
				if ((this._UniqueUserID != value))
				{
					this._UniqueUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeadID", DbType="BigInt")]
		public System.Nullable<long> LeadID
		{
			get
			{
				return this._LeadID;
			}
			set
			{
				if ((this._LeadID != value))
				{
					this._LeadID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewUser", DbType="Bit")]
		public System.Nullable<bool> NewUser
		{
			get
			{
				return this._NewUser;
			}
			set
			{
				if ((this._NewUser != value))
				{
					this._NewUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedCaptcha_DUE_IP", DbType="Bit")]
		public System.Nullable<bool> NeedCaptcha_DUE_IP
		{
			get
			{
				return this._NeedCaptcha_DUE_IP;
			}
			set
			{
				if ((this._NeedCaptcha_DUE_IP != value))
				{
					this._NeedCaptcha_DUE_IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAllowed_IP", DbType="Int")]
		public System.Nullable<int> MaxAllowed_IP
		{
			get
			{
				return this._MaxAllowed_IP;
			}
			set
			{
				if ((this._MaxAllowed_IP != value))
				{
					this._MaxAllowed_IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count_IP", DbType="Int")]
		public System.Nullable<int> Count_IP
		{
			get
			{
				return this._Count_IP;
			}
			set
			{
				if ((this._Count_IP != value))
				{
					this._Count_IP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpiredIPAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiredIPAt
		{
			get
			{
				return this._ExpiredIPAt;
			}
			set
			{
				if ((this._ExpiredIPAt != value))
				{
					this._ExpiredIPAt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
